// DealDrop Mock Data — Simulates full Supabase backend for demo

export const MOCK_USERS = [
  {
    id: 'user-001',
    email: 'priya@demo.com',
    full_name: 'Priya Sharma',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=100&auto=format&fit=crop',
    passport_level: 'Explorer',
    deal_passport_stamps: 12,
    preferred_radius_km: 3,
    preferred_categories: ['food', 'fitness'],
    total_savings: 248.50,
    reward_points: 1250,
  },
  {
    id: 'user-002',
    email: 'marcus@demo.com',
    full_name: 'Marcus Vance',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100&auto=format&fit=crop',
    passport_level: 'Hunter',
    deal_passport_stamps: 28,
    preferred_radius_km: 5,
    preferred_categories: ['fashion', 'electronics'],
    total_savings: 512.00,
    reward_points: 3800,
  },
  {
    id: 'user-003',
    email: 'sarah@demo.com',
    full_name: 'Sarah Jenkins',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=100&auto=format&fit=crop',
    passport_level: 'Newcomer',
    deal_passport_stamps: 3,
    preferred_radius_km: 2,
    preferred_categories: ['food', 'wellness'],
    total_savings: 45.00,
    reward_points: 300,
  }
];

export const MOCK_RETAILERS = [
  {
    id: 'r-001',
    shop_name: "The Butcher's Table",
    address: "42 MG Road, Bangalore",
    category: 'food',
    rating: 4.8,
    avatar_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=200&auto=format&fit=crop',
    distance_km: 0.4,
  },
  {
    id: 'r-002',
    shop_name: "Blue Bottle Coffee",
    address: "12 Indiranagar, Bangalore",
    category: 'food',
    rating: 4.6,
    avatar_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=200&auto=format&fit=crop',
    distance_km: 0.7,
  },
  {
    id: 'r-003',
    shop_name: "SneakerHead NYC",
    address: "5 Commercial Street, Bangalore",
    category: 'fashion',
    rating: 4.9,
    avatar_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=200&auto=format&fit=crop',
    distance_km: 1.2,
  },
  {
    id: 'r-004',
    shop_name: "Zen Yoga Studio",
    address: "18 Koramangala, Bangalore",
    category: 'wellness',
    rating: 4.7,
    avatar_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=200&auto=format&fit=crop',
    distance_km: 0.9,
  },
  {
    id: 'r-005',
    shop_name: "FreshMart Grocery",
    address: "7 HSR Layout, Bangalore",
    category: 'grocery',
    rating: 4.3,
    avatar_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=200&auto=format&fit=crop',
    distance_km: 0.3,
  },
  {
    id: 'r-006',
    shop_name: "Urban Threads",
    address: "22 Brigade Road, Bangalore",
    category: 'fashion',
    rating: 4.5,
    avatar_url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=200&auto=format&fit=crop',
    distance_km: 1.8,
  },
];

const futureTime = (hours: number) => new Date(Date.now() + hours * 3600000).toISOString();

export const MOCK_DEALS = [
  {
    id: 'deal-001',
    retailer_id: 'r-001',
    retailers: MOCK_RETAILERS[0],
    product_name: '50% Off Signature Ribs',
    description: "Our award-winning slow-smoked baby back ribs, marinated for 24 hours. Available only during the pulse window. Includes sides.",
    category: 'food',
    original_price: 38.00,
    current_price: 19.00,
    discount_percent: 50,
    quantity_total: 20,
    quantity_remaining: 7,
    expiry_time: futureTime(2),
    image_url: 'https://images.unsplash.com/photo-1544025162-836901980a56?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: false,
    distance_km: 0.4,
    urgency_level: 'high',
  },
  {
    id: 'deal-002',
    retailer_id: 'r-002',
    retailers: MOCK_RETAILERS[1],
    product_name: 'Free Oat Latte with Pastry',
    description: "Our signature house-roasted oat latte paired with a freshly baked almond croissant. Limited to first 30 pulse claimants.",
    category: 'food',
    original_price: 14.00,
    current_price: 5.50,
    discount_percent: 61,
    quantity_total: 30,
    quantity_remaining: 14,
    expiry_time: futureTime(1),
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: false,
    distance_km: 0.7,
    urgency_level: 'critical',
  },
  {
    id: 'deal-003',
    retailer_id: 'r-003',
    retailers: MOCK_RETAILERS[2],
    product_name: 'Yeezy Boost 350 – Squad Drop',
    description: "Exclusive squad-powered flash deal. When 15 people join, the group discount unlocks instantly. Original retail price applies individually.",
    category: 'fashion',
    original_price: 220.00,
    current_price: 154.00,
    discount_percent: 30,
    quantity_total: 15,
    quantity_remaining: 15,
    expiry_time: futureTime(4),
    image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: true,
    flash_mob_target: 15,
    flash_mob_discount: 30,
    distance_km: 1.2,
    urgency_level: 'medium',
  },
  {
    id: 'deal-004',
    retailer_id: 'r-004',
    retailers: MOCK_RETAILERS[3],
    product_name: 'Drop-in Yoga Class Pass',
    description: "Join any single walk-in yoga session today at Zen Studio. All skill levels welcome. Mat provided.",
    category: 'wellness',
    original_price: 20.00,
    current_price: 9.00,
    discount_percent: 55,
    quantity_total: 12,
    quantity_remaining: 4,
    expiry_time: futureTime(3),
    image_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: false,
    distance_km: 0.9,
    urgency_level: 'high',
  },
  {
    id: 'deal-005',
    retailer_id: 'r-005',
    retailers: MOCK_RETAILERS[4],
    product_name: 'Organic Veggie Box – Surplus Pack',
    description: "End-of-day surplus organic vegetables curated into a value box. Zero waste, maximum nutrition. Good for 2-3 meals.",
    category: 'grocery',
    original_price: 25.00,
    current_price: 10.00,
    discount_percent: 60,
    quantity_total: 10,
    quantity_remaining: 2,
    expiry_time: futureTime(0.5),
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: false,
    distance_km: 0.3,
    urgency_level: 'critical',
  },
  {
    id: 'deal-006',
    retailer_id: 'r-006',
    retailers: MOCK_RETAILERS[5],
    product_name: '2-for-1 Summer Shirts – Flash Mob',
    description: "Buy one summer shirt, get one free when the squad reaches 10 people. Pick your style in-store.",
    category: 'fashion',
    original_price: 60.00,
    current_price: 30.00,
    discount_percent: 50,
    quantity_total: 20,
    quantity_remaining: 20,
    expiry_time: futureTime(5),
    image_url: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?q=80&w=800&auto=format&fit=crop',
    status: 'active',
    is_flash_mob: true,
    flash_mob_target: 10,
    flash_mob_discount: 50,
    distance_km: 1.8,
    urgency_level: 'low',
  },
];

export const MOCK_SQUADS = [
  { id: 'sq-001', deal_id: 'deal-003', target_count: 15, current_count: 11, status: 'forming', expires_at: futureTime(4) },
  { id: 'sq-002', deal_id: 'deal-006', target_count: 10, current_count: 4, status: 'forming', expires_at: futureTime(5) },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n-1', type: 'location', title: 'Pulse Match Nearby!',
    message: "You just walked into the 500m radius for a 50% Off Ribs deal. Claim before 2PM.",
    time: '2m ago', unread: true
  },
  {
    id: 'n-2', type: 'squad', title: 'Squad Almost There!',
    message: "Your Flash Squad for Yeezy Boost needs just 4 more people. Share the link!",
    time: '15m ago', unread: true
  },
  {
    id: 'n-3', type: 'alert', title: 'Deal Expiring Soon',
    message: "Your saved deal 'Organic Veggie Box' is down to 2 remaining items. Grab it!",
    time: '1h ago', unread: true
  },
  {
    id: 'n-4', type: 'system', title: 'New AI Personalization',
    message: "We updated your Pulse Radius to prioritize Wellness & Food drops based on your history.",
    time: '1d ago', unread: false
  },
  {
    id: 'n-5', type: 'system', title: 'Badge Earned!',
    message: "Congrats! You earned the 'Explorer' badge for claiming 10+ deals. Check your Passport.",
    time: '2d ago', unread: false
  },
];

export const MOCK_ACTIVITY = [
  { id: 'a-1', type: 'claim', label: "Claimed '50% Off Ribs'", time: "Today 9:00 AM", value: '+$19 saved', deal_id: 'deal-001' },
  { id: 'a-2', type: 'review', label: "Rated Blue Bottle Coffee ⭐⭐⭐⭐⭐", time: "Today 10:00 AM", value: '+50 pts', deal_id: 'deal-002' },
  { id: 'a-3', type: 'squad', label: "Joined Yeezy Squad #11", time: "Yesterday", value: 'Pending', deal_id: 'deal-003' },
  { id: 'a-4', type: 'claim', label: "Claimed Yoga Class Pass", time: "2 days ago", value: '+$11 saved', deal_id: 'deal-004' },
];
